[package]
name = "necra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k256 = {version = "0.9", features = ["ecdsa","keccak256"]}
thiserror = "1"
log = "0.4"
